#let rhoe-artifact(id: none, title: "", carrier: "", genre: "", composition-grammar: "", brand: none, critic-profile: none, body) = [
  #body
]

#let rhoe-front-matter(body) = [#body]
#let rhoe-main-matter(body) = [#body]
#let rhoe-back-matter(body) = [#body]
#let rhoe-section(title: "", id: none, body) = [= #title #body]
#let rhoe-subsection(title: "", id: none, body) = [== #title #body]
#let rhoe-subsubsection(title: "", id: none, body) = [=== #title #body]
#let rhoe-ref(target: "", mode: "full") = [#target]
#let rhoe-image(src: "", alt: "") = image(src, alt: alt)
#let rhoe-table(id: none, body) = [#body]

#let rhoe-frameset(id: none, aspect: none, body) = [#body]
#let rhoe-frame(id: none, shell-role: none, shell: none, shell-pack: none, continuation: none, brand: none, critic-profile: none, body) = [#body]
#let rhoe-frame-section(title: "", body) = [= #title #body]
#let rhoe-appendix-frameset(id: none, body) = [#body]
#let rhoe-zone(role: "main", body) = [#body]

#let rhoe-codex(title: "", id: none, body) = [#body]
#let rhoe-chapter(title: "", id: none, body) = [#body]
#let rhoe-spread(title: "", id: none, body) = [#body]
#let rhoe-appendix(title: "", id: none, body) = [#body]
#let rhoe-reference-apparatus(id: none, body) = [#body]

#let rhoe-stream(id: none, body) = [#body]
#let rhoe-file-segment(path: "", id: none, body) = [#body]
#let rhoe-anchor(id: "", body) = [#body]
#let rhoe-support-matter(id: none, body) = [#body]
#let rhoe-jump(target: "", id: none, body) = [#body]

#let rhoe-tableau-document(title: "", id: none, body) = [#body]
#let rhoe-page-family(title: "", id: none, body) = [#body]
#let rhoe-tableau-page(title: "", id: none, body) = [#body]
#let rhoe-region-group(id: none, body) = [#body]
#let rhoe-hero-region(id: none, body) = [#body]
#let rhoe-support-region(id: none, body) = [#body]

#let rhoe-field-document(title: "", id: none, body) = [#body]
#let rhoe-sheet(title: "", id: none, body) = [#body]
#let rhoe-perimeter(title: "", id: none, body) = [#body]
#let rhoe-top-band(title: "", id: none, body) = [#body]
#let rhoe-bottom-band(title: "", id: none, body) = [#body]
#let rhoe-side-band(title: "", id: none, body) = [#body]
#let rhoe-region(title: "", id: none, body) = [#body]

#let rhoe-register(title: "", id: none, body) = [#body]
#let rhoe-collection(name: "", id: none, body) = [#body]
#let rhoe-schema(ref: "", id: none, body) = [#body]
#let rhoe-record(id: none, body) = [#body]
#let rhoe-form(title: "", id: none, body) = [#body]
#let rhoe-dashboard(id: none, body) = [#body]
#let rhoe-constraint(id: none, body) = [#body]

#let rhoe-box(title: "", id: none, body) = [#body]
#let rhoe-tag-catalog(id: none, body) = [#body]
#let rhoe-fragment(id: none, body) = [#body]
#let rhoe-subcollection(title: "", id: none, body) = [#body]
#let rhoe-cluster(title: "", id: none, body) = [#body]
#let rhoe-saved-view(title: "", id: none, body) = [#body]

#let rhoe-thread(id: none, body) = [#body]
#let rhoe-participant-profile(id: none, body) = [#body]
#let rhoe-topic-briefing(id: none, body) = [#body]
#let rhoe-conduct-doctrine(id: none, body) = [#body]
#let rhoe-episode(title: "", id: none, body) = [#body]
#let rhoe-branch(title: "", id: none, body) = [#body]
#let rhoe-turn(speaker: "", id: none, body) = [#body]
#let rhoe-attachment-ref(target: "", id: none, body) = [#body]
#let rhoe-outcome(id: none, body) = [#body]
